// Centralized Role and Permission Definitions for Last-Mile Delivery Tracking System

export const ROLES = {
  ADMIN: 'ADMIN',
  DISPATCHER: 'DISPATCHER',
  DELIVERY_AGENT: 'DELIVERY_AGENT',
  WAREHOUSE_STAFF: 'WAREHOUSE_STAFF',
  CUSTOMER: 'CUSTOMER',
}

export const PERMISSIONS = {
  // User Management
  USER_VIEW_ALL: 'USER_VIEW_ALL',
  USER_MANAGE_ROLES: 'USER_MANAGE_ROLES',
  USER_DELETE: 'USER_DELETE',
  USER_VIEW_AGENTS: 'USER_VIEW_AGENTS',
  USER_UPDATE_OWN_AVAILABILITY: 'USER_UPDATE_OWN_AVAILABILITY',
  USER_VIEW_OWN_PROFILE: 'USER_VIEW_OWN_PROFILE',
  USER_UPDATE_OWN_PROFILE: 'USER_UPDATE_OWN_PROFILE',

  // Order Management
  ORDER_VIEW_ALL: 'ORDER_VIEW_ALL',
  ORDER_VIEW_ASSIGNED: 'ORDER_VIEW_ASSIGNED',
  ORDER_VIEW_WAREHOUSE: 'ORDER_VIEW_WAREHOUSE',
  ORDER_VIEW_OWN: 'ORDER_VIEW_OWN',
  ORDER_CREATE: 'ORDER_CREATE',
  ORDER_CREATE_ON_BEHALF: 'ORDER_CREATE_ON_BEHALF',
  ORDER_RESCHEDULE: 'ORDER_RESCHEDULE',

  // Delivery & Dispatch Operations
  DELIVERY_VIEW_ALL: 'DELIVERY_VIEW_ALL',
  DELIVERY_ASSIGN: 'DELIVERY_ASSIGN',
  DELIVERY_REASSIGN: 'DELIVERY_REASSIGN',
  DELIVERY_AUTO_ASSIGN: 'DELIVERY_AUTO_ASSIGN',
  DELIVERY_STATUS_UPDATE: 'DELIVERY_STATUS_UPDATE',
  DELIVERY_LOCATION_UPDATE: 'DELIVERY_LOCATION_UPDATE',
  PROOF_OF_DELIVERY_UPLOAD: 'PROOF_OF_DELIVERY_UPLOAD',

  // Warehouse & Hub Management
  WAREHOUSE_VIEW: 'WAREHOUSE_VIEW',
  WAREHOUSE_MANAGE: 'WAREHOUSE_MANAGE',
  PACKAGE_PROCESS: 'PACKAGE_PROCESS',
  PACKAGE_HANDOVER: 'PACKAGE_HANDOVER',

  // Pricing & Coverage Zones
  ZONE_VIEW: 'ZONE_VIEW',
  ZONE_MANAGE: 'ZONE_MANAGE',
  RATE_VIEW: 'RATE_VIEW',
  RATE_MANAGE: 'RATE_MANAGE',

  // Partner Applications
  PARTNER_APP_SUBMIT: 'PARTNER_APP_SUBMIT',
  PARTNER_APP_VIEW_OWN: 'PARTNER_APP_VIEW_OWN',
  PARTNER_APP_VIEW_ALL: 'PARTNER_APP_VIEW_ALL',
  PARTNER_APP_REVIEW: 'PARTNER_APP_REVIEW',

  // Reports & System Configuration
  REPORT_VIEW_OPERATIONAL: 'REPORT_VIEW_OPERATIONAL',
  REPORT_VIEW_ALL: 'REPORT_VIEW_ALL',
  AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',
  SYSTEM_SETTINGS_MANAGE: 'SYSTEM_SETTINGS_MANAGE',
}

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),

  [ROLES.DISPATCHER]: [
    PERMISSIONS.USER_VIEW_AGENTS,
    PERMISSIONS.USER_VIEW_OWN_PROFILE,
    PERMISSIONS.USER_UPDATE_OWN_PROFILE,
    PERMISSIONS.ORDER_VIEW_ALL,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_CREATE_ON_BEHALF,
    PERMISSIONS.ORDER_RESCHEDULE,
    PERMISSIONS.DELIVERY_VIEW_ALL,
    PERMISSIONS.DELIVERY_ASSIGN,
    PERMISSIONS.DELIVERY_REASSIGN,
    PERMISSIONS.DELIVERY_AUTO_ASSIGN,
    PERMISSIONS.DELIVERY_STATUS_UPDATE,
    PERMISSIONS.WAREHOUSE_VIEW,
    PERMISSIONS.PACKAGE_PROCESS,
    PERMISSIONS.PACKAGE_HANDOVER,
    PERMISSIONS.ZONE_VIEW,
    PERMISSIONS.RATE_VIEW,
    PERMISSIONS.PARTNER_APP_VIEW_ALL,
    PERMISSIONS.PARTNER_APP_REVIEW,
    PERMISSIONS.REPORT_VIEW_OPERATIONAL,
    PERMISSIONS.AUDIT_LOG_VIEW,
  ],

  [ROLES.DELIVERY_AGENT]: [
    PERMISSIONS.USER_VIEW_OWN_PROFILE,
    PERMISSIONS.USER_UPDATE_OWN_PROFILE,
    PERMISSIONS.USER_UPDATE_OWN_AVAILABILITY,
    PERMISSIONS.ORDER_VIEW_ASSIGNED,
    PERMISSIONS.DELIVERY_VIEW_ASSIGNED,
    PERMISSIONS.DELIVERY_STATUS_UPDATE,
    PERMISSIONS.DELIVERY_LOCATION_UPDATE,
    PERMISSIONS.PROOF_OF_DELIVERY_UPLOAD,
    PERMISSIONS.ZONE_VIEW,
  ],

  [ROLES.WAREHOUSE_STAFF]: [
    PERMISSIONS.USER_VIEW_OWN_PROFILE,
    PERMISSIONS.USER_UPDATE_OWN_PROFILE,
    PERMISSIONS.USER_VIEW_AGENTS,
    PERMISSIONS.ORDER_VIEW_WAREHOUSE,
    PERMISSIONS.DELIVERY_STATUS_UPDATE,
    PERMISSIONS.WAREHOUSE_VIEW,
    PERMISSIONS.PACKAGE_PROCESS,
    PERMISSIONS.PACKAGE_HANDOVER,
    PERMISSIONS.ZONE_VIEW,
  ],

  [ROLES.CUSTOMER]: [
    PERMISSIONS.USER_VIEW_OWN_PROFILE,
    PERMISSIONS.USER_UPDATE_OWN_PROFILE,
    PERMISSIONS.ORDER_VIEW_OWN,
    PERMISSIONS.ORDER_CREATE,
    PERMISSIONS.ORDER_RESCHEDULE,
    PERMISSIONS.PARTNER_APP_SUBMIT,
    PERMISSIONS.PARTNER_APP_VIEW_OWN,
    PERMISSIONS.ZONE_VIEW,
  ],
}

/**
 * Checks if a user has a specific permission.
 * Supports both pre-computed user.permissions array and role-based fallback.
 */
export function hasPermission(user, permission) {
  if (!user) return false
  if (user.role === ROLES.ADMIN) return true

  if (Array.isArray(user.permissions) && user.permissions.includes(permission)) {
    return true
  }

  const rolePerms = ROLE_PERMISSIONS[user.role]
  return rolePerms ? rolePerms.includes(permission) : false
}

/**
 * Checks if a user has any of the given roles.
 */
export function hasRole(user, ...roles) {
  if (!user || !user.role) return false
  return roles.includes(user.role)
}
