package com.lastmile.delivery.service;
import com.lastmile.delivery.dto.request.*;
import com.lastmile.delivery.dto.response.OrderResponse;
import com.lastmile.delivery.entity.*;
import com.lastmile.delivery.repository.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.*;
import java.util.*;

@Service @Transactional
public class OrderService {
 private final DeliveryOrderRepository orders; private final UserRepository users; private final ZoneRepository zones; private final RateCardRepository rates; private final CodChargeRepository cod; private final OrderTrackingHistoryRepository tracking; private final DeliveryAttemptRepository attempts;
 public OrderService(DeliveryOrderRepository orders, UserRepository users, ZoneRepository zones, RateCardRepository rates, CodChargeRepository cod, OrderTrackingHistoryRepository tracking, DeliveryAttemptRepository attempts){this.orders=orders;this.users=users;this.zones=zones;this.rates=rates;this.cod=cod;this.tracking=tracking;this.attempts=attempts;}
 public OrderResponse create(String email, CreateOrderRequest r){ User customer=user(email); Zone pickup=zone(r.pickupZoneId()), drop=zone(r.dropZoneId()); BigDecimal volume=r.lengthCm().multiply(r.widthCm()).multiply(r.heightCm()).divide(BigDecimal.valueOf(5000),3,RoundingMode.HALF_UP); BigDecimal weight=r.actualWeightKg().max(volume); RateCard rate=rates.findByPickupZoneIdAndDropZoneIdAndOrderType(pickup.getId(),drop.getId(),r.orderType()).orElseThrow(()->new IllegalArgumentException("No rate card for the selected zones and order type")); BigDecimal base=weight.multiply(rate.getRatePerKg()).max(rate.getMinimumCharge()).setScale(2,RoundingMode.HALF_UP); BigDecimal surcharge=r.paymentType()==PaymentType.COD?cod.findByOrderType(r.orderType()).map(CodCharge::getSurcharge).orElse(BigDecimal.ZERO):BigDecimal.ZERO; DeliveryOrder o=new DeliveryOrder(); o.setCustomer(customer);o.setPickupAddress(r.pickupAddress());o.setDropAddress(r.dropAddress());o.setPickupZone(pickup);o.setDropZone(drop);o.setLengthCm(r.lengthCm());o.setWidthCm(r.widthCm());o.setHeightCm(r.heightCm());o.setActualWeightKg(r.actualWeightKg());o.setVolumetricWeightKg(volume);o.setChargeableWeightKg(weight);o.setOrderType(r.orderType());o.setPaymentType(r.paymentType());o.setBaseCharge(base);o.setCodSurcharge(surcharge);o.setFinalCharge(base.add(surcharge));o.setStatus(OrderStatus.PLACED); o=orders.save(o); history(o,customer); return map(o); }
 public List<OrderResponse> mine(String email){User u=user(email); return (u.getRole()==Role.DELIVERY_AGENT?orders.findByDeliveryAgentIdOrderByUpdatedAtDesc(u.getId()):u.getRole()==Role.ADMIN?orders.findAll():orders.findByCustomerIdOrderByCreatedAtDesc(u.getId())).stream().map(this::map).toList();}
 public OrderResponse get(String email, Long id){DeliveryOrder o=order(id); User u=user(email); if(u.getRole()!=Role.ADMIN&&!o.getCustomer().getId().equals(u.getId())&&(o.getDeliveryAgent()==null||!o.getDeliveryAgent().getId().equals(u.getId()))) throw new org.springframework.security.access.AccessDeniedException("Not permitted"); return map(o);}
 public OrderResponse transition(String email,Long id,StatusUpdateRequest r){DeliveryOrder o=order(id);User actor=user(email); if(actor.getRole()==Role.DELIVERY_AGENT&&(o.getDeliveryAgent()==null||!o.getDeliveryAgent().getId().equals(actor.getId())))throw new org.springframework.security.access.AccessDeniedException("Not assigned"); if(!allowed(o.getStatus(),r.status()))throw new IllegalArgumentException("Invalid status transition"); o.setStatus(r.status()); if(r.status()==OrderStatus.FAILED||r.status()==OrderStatus.DELIVERED){DeliveryAttempt a=new DeliveryAttempt();a.setOrder(o);a.setDeliveryAgent(actor);a.setAttemptNumber((int)attempts.countByOrderId(id)+1);a.setStatus(r.status()==OrderStatus.DELIVERED?AttemptStatus.DELIVERED:AttemptStatus.FAILED);a.setFailureReason(r.failureReason());attempts.save(a);} history(o,actor);return map(o);}
 public OrderResponse assign(Long id,Long agentId,String email){DeliveryOrder o=order(id);User agent=users.findById(agentId).orElseThrow();if(agent.getRole()!=Role.DELIVERY_AGENT)throw new IllegalArgumentException("User is not a delivery agent");o.setDeliveryAgent(agent);history(o,user(email));return map(o);}
 private boolean allowed(OrderStatus a,OrderStatus b){return switch(a){case PLACED,RESCHEDULED->b==OrderStatus.PICKED_UP;case PICKED_UP->b==OrderStatus.IN_TRANSIT;case IN_TRANSIT->b==OrderStatus.OUT_FOR_DELIVERY;case OUT_FOR_DELIVERY->b==OrderStatus.DELIVERED||b==OrderStatus.FAILED;case FAILED->b==OrderStatus.RESCHEDULED;default->false;};}
 private void history(DeliveryOrder o,User actor){OrderTrackingHistory h=new OrderTrackingHistory();h.setOrder(o);h.setActor(actor);h.setStatus(o.getStatus());tracking.save(h);} private User user(String e){return users.findByEmailIgnoreCase(e).orElseThrow();}private Zone zone(Long id){return zones.findById(id).orElseThrow();}private DeliveryOrder order(Long id){return orders.findById(id).orElseThrow();}private OrderResponse map(DeliveryOrder o){return new OrderResponse(o.getId(),o.getCustomer().getId(),o.getDeliveryAgent()==null?null:o.getDeliveryAgent().getId(),o.getPickupAddress(),o.getDropAddress(),o.getPickupZone().getName(),o.getDropZone().getName(),o.getOrderType(),o.getPaymentType(),o.getStatus(),o.getChargeableWeightKg(),o.getFinalCharge(),o.getCreatedAt());}
}
