spring.application.name=last-mile-delivery

spring.config.import=optional:file:.env[.properties]

server.port=${PORT:8080}

app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:5173}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/last_mile_delivery?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# Brevo SMTP
spring.mail.host=${BREVO_SMTP_HOST:smtp-relay.brevo.com}
spring.mail.port=${BREVO_SMTP_PORT:587}
spring.mail.username=${BREVO_SMTP_USERNAME}
spring.mail.password=${BREVO_SMTP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=${BREVO_FROM_EMAIL}
